# --------------------------------
# Geyser Configuration File
# 
# A bridge between Minecraft: Bedrock Edition and Minecraft: Java Edition.
# 
# GitHub: https://github.com/GeyserMC/Geyser
# Discord: https://discord.gg/geysermc
# Wiki: https://geysermc.org/wiki
# 
# NOTICE: See https://geysermc.org/wiki/geyser/setup/ for the setup guide. Many video tutorials are outdated.
# In most cases, especially with server hosting providers, further hosting-specific configuration is required.
# --------------------------------

notify-on-new-bedrock-update: false

# Do not change!
config-version: 7
